// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.deepnet;

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    @JvmField var capacity: Int = 0
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

    companion object {
        internal fun alloc(size: Int = 0) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_deepnet_mobile_rustbuffer_alloc(size, status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: Int, len: Int, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity
            buf.len = len
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = rustCall() { status ->
            _UniFFILib.INSTANCE.ffi_deepnet_mobile_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setInt(0, value.capacity)
        pointer.setInt(4, value.len)
        pointer.setPointer(8, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getInt(0))
        value.writeField("len", pointer.getInt(4))
        value.writeField("data", pointer.getPointer(8))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): Int

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity.toLong()).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
@Structure.FieldOrder("code", "error_buf")
internal open class RustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: RustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == 0.toByte()
    }

    fun isError(): Boolean {
        return code == 1.toByte()
    }

    fun isPanic(): Boolean {
        return code == 2.toByte()
    }
}

class InternalException(message: String) : Exception(message)

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: Exception> rustCallWithError(errorHandler: CallStatusErrorHandler<E>, callback: (RustCallStatus) -> U): U {
    var status = RustCallStatus();
    val return_value = callback(status)
    checkCallStatus(errorHandler, status)
    return return_value
}

// Check RustCallStatus and throw an error if the call wasn't successful
private fun<E: Exception> checkCallStatus(errorHandler: CallStatusErrorHandler<E>, status: RustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
object NullCallStatusErrorHandler: CallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> rustCall(callback: (RustCallStatus) -> U): U {
    return rustCallWithError(NullCallStatusErrorHandler, callback);
}

// IntegerType that matches Rust's `usize` / C's `size_t`
public class USize(value: Long = 0) : IntegerType(Native.SIZE_T_SIZE, value, true) {
    // This is needed to fill in the gaps of IntegerType's implementation of Number for Kotlin.
    override fun toByte() = toInt().toByte()
    // Needed until https://youtrack.jetbrains.com/issue/KT-47902 is fixed.
    @Deprecated("`toInt().toChar()` is deprecated")
    override fun toChar() = toInt().toChar()
    override fun toShort() = toInt().toShort()

    fun writeToBuffer(buf: ByteBuffer) {
        // Make sure we always write usize integers using native byte-order, since they may be
        // casted to pointer values
        buf.order(ByteOrder.nativeOrder())
        try {
            when (Native.SIZE_T_SIZE) {
                4 -> buf.putInt(toInt())
                8 -> buf.putLong(toLong())
                else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
            }
        } finally {
            buf.order(ByteOrder.BIG_ENDIAN)
        }
    }

    companion object {
        val size: Int
            get() = Native.SIZE_T_SIZE

        fun readFromBuffer(buf: ByteBuffer) : USize {
            // Make sure we always read usize integers using native byte-order, since they may be
            // casted from pointer values
            buf.order(ByteOrder.nativeOrder())
            try {
                return when (Native.SIZE_T_SIZE) {
                    4 -> USize(buf.getInt().toLong())
                    8 -> USize(buf.getLong())
                    else -> throw RuntimeException("Invalid SIZE_T_SIZE: ${Native.SIZE_T_SIZE}")
                }
            } finally {
                buf.order(ByteOrder.BIG_ENDIAN)
            }
        }
    }
}


// Map handles to objects
//
// This is used when the Rust code expects an opaque pointer to represent some foreign object.
// Normally we would pass a pointer to the object, but JNA doesn't support getting a pointer from an
// object reference , nor does it support leaking a reference to Rust.
//
// Instead, this class maps USize values to objects so that we can pass a pointer-sized type to
// Rust when it needs an opaque pointer.
//
// TODO: refactor callbacks to use this class
internal class UniFfiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<USize, T>()
    // Use AtomicInteger for our counter, since we may be on a 32-bit system.  4 billion possible
    // values seems like enough. If somehow we generate 4 billion handles, then this will wrap
    // around back to zero and we can assume the first handle generated will have been dropped by
    // then.
    private val counter = java.util.concurrent.atomic.AtomicInteger(0)

    val size: Int
        get() = map.size

    fun insert(obj: T): USize {
        val handle = USize(counter.getAndAdd(1).toLong())
        map.put(handle, obj)
        return handle
    }

    fun get(handle: USize): T? {
        return map.get(handle)
    }

    fun remove(handle: USize): T? {
        return map.remove(handle)
    }
}

// FFI type for Rust future continuations
internal interface UniFffiRustFutureContinuationCallbackType : com.sun.jna.Callback {
    fun callback(continuationHandle: USize, pollResult: Short);
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_deepnet"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface _UniFFILib : Library {
    companion object {
        internal val INSTANCE: _UniFFILib by lazy {
            loadIndirect<_UniFFILib>(componentName = "deepnet")
            .also { lib: _UniFFILib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
    }

    fun uniffi_deepnet_mobile_fn_func_deep_net_init(`storageDir`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun uniffi_deepnet_mobile_fn_func_deep_net_last_sync(_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_deep_net_pending_count(_uniffi_out_err: RustCallStatus, 
    ): Int
    fun uniffi_deepnet_mobile_fn_func_deep_net_sync(_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_federation_disconnect(_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_deepnet_mobile_fn_func_federation_get_members(_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_federation_register(`serverUrl`: RustBuffer.ByValue,`deviceName`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_federation_status(_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_teambook_broadcast(`content`: RustBuffer.ByValue,`channel`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_teambook_dm(`toAiId`: RustBuffer.ByValue,`content`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_teambook_get_broadcasts(`limit`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_teambook_get_dms(`limit`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_deepnet_mobile_fn_func_teambook_get_team(_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_deepnet_mobile_rustbuffer_alloc(`size`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_deepnet_mobile_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_deepnet_mobile_rustbuffer_free(`buf`: RustBuffer.ByValue,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun ffi_deepnet_mobile_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Int,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_deepnet_mobile_rust_future_continuation_callback_set(`callback`: UniFffiRustFutureContinuationCallbackType,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_poll_u8(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_u8(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_u8(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_u8(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun ffi_deepnet_mobile_rust_future_poll_i8(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_i8(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_i8(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_i8(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Byte
    fun ffi_deepnet_mobile_rust_future_poll_u16(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_u16(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_u16(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_u16(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Short
    fun ffi_deepnet_mobile_rust_future_poll_i16(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_i16(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_i16(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_i16(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Short
    fun ffi_deepnet_mobile_rust_future_poll_u32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_u32(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_u32(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_u32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun ffi_deepnet_mobile_rust_future_poll_i32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_i32(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_i32(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_i32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Int
    fun ffi_deepnet_mobile_rust_future_poll_u64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_u64(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_u64(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_u64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun ffi_deepnet_mobile_rust_future_poll_i64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_i64(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_i64(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_i64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Long
    fun ffi_deepnet_mobile_rust_future_poll_f32(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_f32(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_f32(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_f32(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Float
    fun ffi_deepnet_mobile_rust_future_poll_f64(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_f64(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_f64(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_f64(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Double
    fun ffi_deepnet_mobile_rust_future_poll_pointer(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_pointer(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_pointer(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Pointer
    fun ffi_deepnet_mobile_rust_future_poll_rust_buffer(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_rust_buffer(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_rust_buffer(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_deepnet_mobile_rust_future_poll_void(`handle`: Pointer,`uniffiCallback`: USize,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_cancel_void(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_free_void(`handle`: Pointer,
    ): Unit
    fun ffi_deepnet_mobile_rust_future_complete_void(`handle`: Pointer,_uniffi_out_err: RustCallStatus, 
    ): Unit
    fun uniffi_deepnet_mobile_checksum_func_deep_net_init(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_deep_net_last_sync(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_deep_net_pending_count(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_deep_net_sync(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_federation_disconnect(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_federation_get_members(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_federation_register(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_federation_status(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_teambook_broadcast(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_teambook_dm(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_teambook_get_broadcasts(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_teambook_get_dms(
    ): Short
    fun uniffi_deepnet_mobile_checksum_func_teambook_get_team(
    ): Short
    fun ffi_deepnet_mobile_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: _UniFFILib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_deepnet_mobile_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: _UniFFILib) {
    if (lib.uniffi_deepnet_mobile_checksum_func_deep_net_init() != 65102.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_deep_net_last_sync() != 34466.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_deep_net_pending_count() != 47270.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_deep_net_sync() != 35833.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_federation_disconnect() != 21957.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_federation_get_members() != 50323.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_federation_register() != 50495.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_federation_status() != 54616.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_teambook_broadcast() != 38287.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_teambook_dm() != 34111.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_teambook_get_broadcasts() != 34223.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_teambook_get_dms() != 25942.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_deepnet_mobile_checksum_func_teambook_get_team() != 61303.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len)
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): Int {
        val sizeForLength = 4
        val sizeForString = value.length * 3
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}




data class Broadcast (
    var `id`: Long, 
    var `fromAi`: String, 
    var `channel`: String, 
    var `content`: String, 
    var `timestamp`: String
) {
    
    companion object
}

public object FfiConverterTypeBroadcast: FfiConverterRustBuffer<Broadcast> {
    override fun read(buf: ByteBuffer): Broadcast {
        return Broadcast(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: Broadcast) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`fromAi`) +
            FfiConverterString.allocationSize(value.`channel`) +
            FfiConverterString.allocationSize(value.`content`) +
            FfiConverterString.allocationSize(value.`timestamp`)
    )

    override fun write(value: Broadcast, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterString.write(value.`fromAi`, buf)
            FfiConverterString.write(value.`channel`, buf)
            FfiConverterString.write(value.`content`, buf)
            FfiConverterString.write(value.`timestamp`, buf)
    }
}




data class DirectMessage (
    var `id`: Long, 
    var `fromAi`: String, 
    var `toAi`: String, 
    var `content`: String, 
    var `timestamp`: String
) {
    
    companion object
}

public object FfiConverterTypeDirectMessage: FfiConverterRustBuffer<DirectMessage> {
    override fun read(buf: ByteBuffer): DirectMessage {
        return DirectMessage(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: DirectMessage) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`fromAi`) +
            FfiConverterString.allocationSize(value.`toAi`) +
            FfiConverterString.allocationSize(value.`content`) +
            FfiConverterString.allocationSize(value.`timestamp`)
    )

    override fun write(value: DirectMessage, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterString.write(value.`fromAi`, buf)
            FfiConverterString.write(value.`toAi`, buf)
            FfiConverterString.write(value.`content`, buf)
            FfiConverterString.write(value.`timestamp`, buf)
    }
}




data class FederationMember (
    var `memberId`: String, 
    var `memberType`: String, 
    var `displayName`: String, 
    var `status`: String, 
    var `registeredAt`: String
) {
    
    companion object
}

public object FfiConverterTypeFederationMember: FfiConverterRustBuffer<FederationMember> {
    override fun read(buf: ByteBuffer): FederationMember {
        return FederationMember(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: FederationMember) = (
            FfiConverterString.allocationSize(value.`memberId`) +
            FfiConverterString.allocationSize(value.`memberType`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterString.allocationSize(value.`status`) +
            FfiConverterString.allocationSize(value.`registeredAt`)
    )

    override fun write(value: FederationMember, buf: ByteBuffer) {
            FfiConverterString.write(value.`memberId`, buf)
            FfiConverterString.write(value.`memberType`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterString.write(value.`status`, buf)
            FfiConverterString.write(value.`registeredAt`, buf)
    }
}




data class FederationResult (
    var `success`: Boolean, 
    var `deviceId`: String, 
    var `authToken`: String, 
    var `errorMessage`: String?
) {
    
    companion object
}

public object FfiConverterTypeFederationResult: FfiConverterRustBuffer<FederationResult> {
    override fun read(buf: ByteBuffer): FederationResult {
        return FederationResult(
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FederationResult) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterString.allocationSize(value.`deviceId`) +
            FfiConverterString.allocationSize(value.`authToken`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: FederationResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterString.write(value.`deviceId`, buf)
            FfiConverterString.write(value.`authToken`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}




data class MessageResult (
    var `success`: Boolean, 
    var `messageId`: Long, 
    var `errorMessage`: String?
) {
    
    companion object
}

public object FfiConverterTypeMessageResult: FfiConverterRustBuffer<MessageResult> {
    override fun read(buf: ByteBuffer): MessageResult {
        return MessageResult(
            FfiConverterBoolean.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: MessageResult) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterLong.allocationSize(value.`messageId`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: MessageResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterLong.write(value.`messageId`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}




data class SyncResult (
    var `success`: Boolean, 
    var `itemsPushed`: UInt, 
    var `itemsPulled`: UInt, 
    var `errorMessage`: String?
) {
    
    companion object
}

public object FfiConverterTypeSyncResult: FfiConverterRustBuffer<SyncResult> {
    override fun read(buf: ByteBuffer): SyncResult {
        return SyncResult(
            FfiConverterBoolean.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: SyncResult) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterUInt.allocationSize(value.`itemsPushed`) +
            FfiConverterUInt.allocationSize(value.`itemsPulled`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: SyncResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterUInt.write(value.`itemsPushed`, buf)
            FfiConverterUInt.write(value.`itemsPulled`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}




data class TeamMember (
    var `aiId`: String, 
    var `displayName`: String, 
    var `status`: String, 
    var `currentActivity`: String?
) {
    
    companion object
}

public object FfiConverterTypeTeamMember: FfiConverterRustBuffer<TeamMember> {
    override fun read(buf: ByteBuffer): TeamMember {
        return TeamMember(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: TeamMember) = (
            FfiConverterString.allocationSize(value.`aiId`) +
            FfiConverterString.allocationSize(value.`displayName`) +
            FfiConverterString.allocationSize(value.`status`) +
            FfiConverterOptionalString.allocationSize(value.`currentActivity`)
    )

    override fun write(value: TeamMember, buf: ByteBuffer) {
            FfiConverterString.write(value.`aiId`, buf)
            FfiConverterString.write(value.`displayName`, buf)
            FfiConverterString.write(value.`status`, buf)
            FfiConverterOptionalString.write(value.`currentActivity`, buf)
    }
}




enum class ConnectionStatus {
    CONNECTED,DISCONNECTED,CONNECTING,OFFLINE,ERROR;
    companion object
}

public object FfiConverterTypeConnectionStatus: FfiConverterRustBuffer<ConnectionStatus> {
    override fun read(buf: ByteBuffer) = try {
        ConnectionStatus.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: ConnectionStatus) = 4

    override fun write(value: ConnectionStatus, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






public object FfiConverterOptionalString: FfiConverterRustBuffer<String?> {
    override fun read(buf: ByteBuffer): String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: String?): Int {
        if (value == null) {
            return 1
        } else {
            return 1 + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




public object FfiConverterSequenceTypeBroadcast: FfiConverterRustBuffer<List<Broadcast>> {
    override fun read(buf: ByteBuffer): List<Broadcast> {
        val len = buf.getInt()
        return List<Broadcast>(len) {
            FfiConverterTypeBroadcast.read(buf)
        }
    }

    override fun allocationSize(value: List<Broadcast>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeBroadcast.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<Broadcast>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeBroadcast.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeDirectMessage: FfiConverterRustBuffer<List<DirectMessage>> {
    override fun read(buf: ByteBuffer): List<DirectMessage> {
        val len = buf.getInt()
        return List<DirectMessage>(len) {
            FfiConverterTypeDirectMessage.read(buf)
        }
    }

    override fun allocationSize(value: List<DirectMessage>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeDirectMessage.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<DirectMessage>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeDirectMessage.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeFederationMember: FfiConverterRustBuffer<List<FederationMember>> {
    override fun read(buf: ByteBuffer): List<FederationMember> {
        val len = buf.getInt()
        return List<FederationMember>(len) {
            FfiConverterTypeFederationMember.read(buf)
        }
    }

    override fun allocationSize(value: List<FederationMember>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeFederationMember.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<FederationMember>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeFederationMember.write(it, buf)
        }
    }
}




public object FfiConverterSequenceTypeTeamMember: FfiConverterRustBuffer<List<TeamMember>> {
    override fun read(buf: ByteBuffer): List<TeamMember> {
        val len = buf.getInt()
        return List<TeamMember>(len) {
            FfiConverterTypeTeamMember.read(buf)
        }
    }

    override fun allocationSize(value: List<TeamMember>): Int {
        val sizeForLength = 4
        val sizeForItems = value.map { FfiConverterTypeTeamMember.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<TeamMember>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.forEach {
            FfiConverterTypeTeamMember.write(it, buf)
        }
    }
}

fun `deepNetInit`(`storageDir`: String): Boolean {
    return FfiConverterBoolean.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_deep_net_init(FfiConverterString.lower(`storageDir`),_status)
})
}


fun `deepNetLastSync`(): String {
    return FfiConverterString.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_deep_net_last_sync(_status)
})
}


fun `deepNetPendingCount`(): UInt {
    return FfiConverterUInt.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_deep_net_pending_count(_status)
})
}


fun `deepNetSync`(): SyncResult {
    return FfiConverterTypeSyncResult.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_deep_net_sync(_status)
})
}


fun `federationDisconnect`() =
    
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_federation_disconnect(_status)
}



fun `federationGetMembers`(): List<FederationMember> {
    return FfiConverterSequenceTypeFederationMember.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_federation_get_members(_status)
})
}


fun `federationRegister`(`serverUrl`: String, `deviceName`: String): FederationResult {
    return FfiConverterTypeFederationResult.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_federation_register(FfiConverterString.lower(`serverUrl`),FfiConverterString.lower(`deviceName`),_status)
})
}


fun `federationStatus`(): ConnectionStatus {
    return FfiConverterTypeConnectionStatus.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_federation_status(_status)
})
}


fun `teambookBroadcast`(`content`: String, `channel`: String): MessageResult {
    return FfiConverterTypeMessageResult.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_teambook_broadcast(FfiConverterString.lower(`content`),FfiConverterString.lower(`channel`),_status)
})
}


fun `teambookDm`(`toAiId`: String, `content`: String): MessageResult {
    return FfiConverterTypeMessageResult.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_teambook_dm(FfiConverterString.lower(`toAiId`),FfiConverterString.lower(`content`),_status)
})
}


fun `teambookGetBroadcasts`(`limit`: UInt): List<Broadcast> {
    return FfiConverterSequenceTypeBroadcast.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_teambook_get_broadcasts(FfiConverterUInt.lower(`limit`),_status)
})
}


fun `teambookGetDms`(`limit`: UInt): List<DirectMessage> {
    return FfiConverterSequenceTypeDirectMessage.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_teambook_get_dms(FfiConverterUInt.lower(`limit`),_status)
})
}


fun `teambookGetTeam`(): List<TeamMember> {
    return FfiConverterSequenceTypeTeamMember.lift(
    rustCall() { _status ->
    _UniFFILib.INSTANCE.uniffi_deepnet_mobile_fn_func_teambook_get_team(_status)
})
}


