//! TURN Credential Verification
//!
//! Verifies time-limited TURN credentials generated by the Discovery Registry.

use base64::{engine::general_purpose::STANDARD, Engine};
use hmac::{Hmac, Mac};
use sha2::Sha256;
use std::time::{SystemTime, UNIX_EPOCH};

type HmacSha256 = Hmac<Sha256>;

/// Verify TURN credentials
///
/// Username format: `{expiry_timestamp}:{user_id}`
/// Password: HMAC-SHA256(secret, username) base64-encoded
pub fn verify_credentials(username: &str, password: &str, secret: &str) -> VerifyResult {
    // Parse expiry from username
    let parts: Vec<&str> = username.splitn(2, ':').collect();
    if parts.len() != 2 {
        return VerifyResult::InvalidFormat;
    }

    let expiry: u64 = match parts[0].parse() {
        Ok(e) => e,
        Err(_) => return VerifyResult::InvalidFormat,
    };

    // Check expiration
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();

    if now > expiry {
        return VerifyResult::Expired;
    }

    // Verify HMAC
    let mut mac = match HmacSha256::new_from_slice(secret.as_bytes()) {
        Ok(m) => m,
        Err(_) => return VerifyResult::InternalError,
    };
    mac.update(username.as_bytes());
    let expected = STANDARD.encode(mac.finalize().into_bytes());

    if password == expected {
        VerifyResult::Valid {
            user_id: parts[1].to_string(),
            expires_in: expiry - now,
        }
    } else {
        VerifyResult::InvalidPassword
    }
}

/// Result of credential verification
#[derive(Debug, Clone)]
pub enum VerifyResult {
    /// Credentials are valid
    Valid {
        user_id: String,
        expires_in: u64,
    },
    /// Credentials have expired
    Expired,
    /// Password doesn't match
    InvalidPassword,
    /// Username format is invalid
    InvalidFormat,
    /// Internal error during verification
    InternalError,
}

impl VerifyResult {
    pub fn is_valid(&self) -> bool {
        matches!(self, VerifyResult::Valid { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_test_credential(user_id: &str, secret: &str, ttl: u64) -> (String, String) {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let expires = now + ttl;

        let username = format!("{}:{}", expires, user_id);

        let mut mac = HmacSha256::new_from_slice(secret.as_bytes()).unwrap();
        mac.update(username.as_bytes());
        let password = STANDARD.encode(mac.finalize().into_bytes());

        (username, password)
    }

    #[test]
    fn test_valid_credential() {
        let secret = "test-secret";
        let (username, password) = generate_test_credential("test-ai", secret, 3600);

        let result = verify_credentials(&username, &password, secret);
        assert!(result.is_valid());

        if let VerifyResult::Valid { user_id, expires_in } = result {
            assert_eq!(user_id, "test-ai");
            assert!(expires_in > 0);
        }
    }

    #[test]
    fn test_invalid_password() {
        let secret = "test-secret";
        let (username, _) = generate_test_credential("test-ai", secret, 3600);

        let result = verify_credentials(&username, "wrong-password", secret);
        assert!(matches!(result, VerifyResult::InvalidPassword));
    }

    #[test]
    fn test_expired_credential() {
        let secret = "test-secret";
        // Create credential that expired 1 hour ago
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let expired = now - 3600;

        let username = format!("{}:test-ai", expired);
        let mut mac = HmacSha256::new_from_slice(secret.as_bytes()).unwrap();
        mac.update(username.as_bytes());
        let password = STANDARD.encode(mac.finalize().into_bytes());

        let result = verify_credentials(&username, &password, secret);
        assert!(matches!(result, VerifyResult::Expired));
    }
}
