// Falling code snippets for the matrix effect
// Edit this file to customize the code that appears in the falling animation
// This is loaded as a global variable, not a module

window.codeSnippets = [
    "import { DuckDBClient } from 'duckdb';",
    "async function remember(content, tags) {",
    "const embeddings = await generateVector(text);",
    "SELECT * FROM notes WHERE created > NOW() - INTERVAL '7 days';",
    "conn.execute('CREATE TABLE IF NOT EXISTS memories');",
    "export const world = { datetime, location, weather };",
    "function parseTimeQuery(when) { return moment(when); }",
    "await redis.publish('teambook:events', JSON.stringify(msg));",
    "const ai_id = crypto.randomUUID().slice(0, 8);",
    "return vectorStore.similaritySearch(query, k=5);",
    "if (priority === 'high') queue.unshift(task);",
    "const pagerank = calculateGraphRank(connections);",
    "await postgres.query('INSERT INTO teambook VALUES ($1, $2)');",
    "fs.writeFileSync(notebookPath, JSON.stringify(data));",
    "class TaskManager extends MCPServer {",
    "session.set('last_operation', { type, result });",
    "const weather = await fetch(`https://api.open-meteo.com`);",
    "function smartTruncate(text, maxChars) {",
    "import Papa from 'papaparse'; // CSV parsing",
    "const db = await DuckDB.connect(':memory:');",
    "logger.info('Notebook v1.0.0 initialized');",
    "return notes.filter(n => n.pinned).sort(byDate);",
    "async function broadcast(channel, message) {",
    "const location = await ipToLocation(ipAddress);",
    "tool.register('remember', notebookRemember);",
    "export default { notebook, task, teambook, world };",
    "const redis = new Redis({ host: 'localhost', port: 6379 });",
    "function detectPriority(text) { /* NLP logic */ }",
    "await standby_mode({ timeout: 180, wakeOn: ['dm', 'mention'] });",
    "const tokens = text.split(/\\s+/).length;",
    "subscriber.on('message', handleEvent);",
    "return similarity > 0.7 ? matches : [];",
    "function formatTimeContextual(timestamp) {",
    "CREATE INDEX idx_embeddings ON notes USING hnsw(embedding);",
    "const tasks = db.prepare('SELECT * FROM tasks WHERE status = ?');",
    "if (ctx.assignee === getCurrentAI()) return task;",
    "await notebook.pin(noteId); // Mark as important",
    "const semanticResults = vectorDB.query(embedding);",
    "export const VERSION = '1.0.0';",
    "function logOperation(op, duration) { stats[op] = duration; }",
    "const pageRank = edges.reduce((acc, e) => acc + e.weight, 0);",
    "await teambook.write({ content, summary, tags });",
    "class OperationTracker { constructor(toolName) {} }",
    "const now = moment().tz('Australia/Melbourne');",
    "return results.map(r => ({ id: r.note_id, score: r.similarity }));",
    "async function evolve(goal, output) { /* Multi-AI collaboration */ }",
    "const lock = await acquireLock(resourceId, timeout);",
    "pub.publish('channel', JSON.stringify({ event: 'note_created' }));",
    "function parseNaturalLanguage(query) { return chronoParse(query); }",
    "const path = require('path').join(__dirname, 'data', 'notebook.db');"
];
